[target.x86_64-pc-windows-msvc]
rustflags = [
    "-L",
    "C:\\Program Files\\Npcap\\Lib\\x64",
    "-C",
    "link-arg=/DEFAULTLIB:wpcap.lib",
    "-C",
    "link-arg=/DEFAULTLIB:delayimp.lib",
    "-C",
    "link-arg=/DELAYLOAD:Packet.dll",
]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"] # 不启用 Rust 自带 C runtime，避免冲突

