//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "app_user")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: String,
    pub username: Option<String>,
    pub password: Option<String>,
    pub gender: Option<String>,
    pub birthday: Option<DateTime>,
    pub avatar: Option<String>,
    pub created_time: Option<DateTime>,
    pub updated_time: Option<DateTime>,
    pub last_login_time: Option<DateTime>,
    pub signup: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
