//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "litemall_device")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub code: Option<String>,
    #[sea_orm(column_name = "reCode")]
    pub re_code: Option<String>,
    pub iccid: Option<String>,
    pub status: Option<i32>,
    #[sea_orm(column_name = "areaId")]
    pub area_id: Option<String>,
    pub remark: Option<String>,
    pub patrolmanid: Option<String>,
    pub addcheckpoint: Option<String>,
    pub customerid: Option<String>,
    pub agentid: Option<String>,
    pub huauserid: Option<String>,
    pub model: Option<String>,
    pub beep: Option<String>,
    pub clockgroupid: Option<String>,
    pub pic: Option<String>,
    pub picpath: Option<String>,
    pub expirydate: Option<DateTime>,
    pub customerusetime: Option<DateTime>,
    pub lastreadtime: Option<DateTime>,
    pub tiptime: Option<DateTime>,
    pub createtime: Option<DateTime>,
    pub smsstatus: Option<i32>,
    pub checkusage: Option<String>,
    pub customername: Option<String>,
    pub customertime: Option<DateTime>,
    pub areaname: Option<String>,
    pub username: Option<String>,
    pub agentname: Option<String>,
    pub clockgroupname: Option<String>,
    pub huausername: Option<String>,
    pub lines: Option<String>,
    pub devicevolumn: Option<String>,
    pub create_time: Option<DateTime>,
    pub recordid: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::litemall_record::Entity",
        from = "Column::Recordid",
        to = "super::litemall_record::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LitemallRecord,
}

impl Related<super::litemall_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LitemallRecord.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
