//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod app_chat;
pub mod app_chat_user;
pub mod app_message_record;
pub mod app_user;
pub mod app_user_friend;
pub mod app_user_message;
pub mod app_user_timeline;
pub mod applet_operation;
pub mod applet_operation_content;
pub mod applet_operation_team;
pub mod applet_operation_team_user;
pub mod applet_pay_centre_record;
pub mod applet_pay_record;
pub mod applet_settings;
pub mod applet_user;
pub mod applet_user_creation;
pub mod litemall_checkpoint;
pub mod litemall_device;
pub mod litemall_record;
