[package]
name = "server-message"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
tower = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }