name: Build Server Wechat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install dependencies (Zig + cargo-zigbuild)
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
          
          ZIG_VERSION=0.11.0
          curl -LO https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz
          tar -xf zig-linux-x86_64-${ZIG_VERSION}.tar.xz
          sudo mv zig-linux-x86_64-${ZIG_VERSION}/zig /usr/local/bin/zig

          cargo install cargo-zigbuild

      - name: Build server-wechat (static binary for CentOS 7)
        working-directory: im-server/service/server-wechat
        run: |
          cargo zigbuild --package server-wechat --target x86_64-unknown-linux-musl --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-wechat-linux-x86_64
          path: im-server/service/server-wechat/target/x86_64-unknown-linux-musl/release/server-wechat
