name: Build Server Wechat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install dependencies (zig + cargo-zigbuild)
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
          curl -L https://github.com/ziglang/zig/releases/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz | tar -xJ
          sudo mv zig-linux-x86_64-0.11.0/zig /usr/local/bin/
          cargo install cargo-zigbuild

      - name: Build server-wechat (static binary for CentOS 7)
        working-directory: im-server/service/server-wechat
        run: |
          cargo zigbuild --target x86_64-unknown-linux-musl --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-wechat-linux-x86_64
          path: im-server/service/server-wechat/target/x86_64-unknown-linux-musl/release/server-wechat
